- type: http
  id: service-kibana-status
  name: Kibana Status
  hosts: ["https://elk6.westeurope.cloudapp.azure.com:5601/api/features"]
  check.response.status: [200]
  schedule: '@every 50s'
  username: "elastic"
  password: "dfLNU9ccMrqwxo365apf"
  ssl:
    certificate_authorities: ["/opt/kibana-7.16.2-linux-x86_64/config/elasticsearch-ca.pem"]
