# Module: beat
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/7.16/metricbeat-module-beat.html

- module: beat
  xpack.enabled: true
  metricsets:
    - stats
    - state
  period: 10s
  hosts: ["http://10.0.0.16:5066","http://10.0.0.16:5067","http://10.0.0.17:5068"]
  username: "elastic"
  password: "dfLNU9ccMrqwxo365apf"
  #ssl.verification_mode: "none"
  http.enabled: true
  http.host: 10.0.0.16,10.0.0.17
  #ssl.certificate_authorities: ["/opt/kibana-7.16.2-linux-x86_64/config/elasticsearch-ca.pem"]
  #http.port: 5067
