# Kibana is served by a back end server. This setting specifies the port to use.
server.port: 5601

# Specifies the address to which the Kibana server will bind. IP addresses and host names are both valid values.
# The default is 'localhost', which usually means remote machines will not be able to connect.
# To allow connections from remote users, set this parameter to a non-loopback address.
server.host: 0.0.0.0

# The Kibana server's name.  This is used for display purposes.
server.name: "elk6"

# The URLs of the Elasticsearch instances to use for all your queries.
elasticsearch.hosts: [ "https://elk6.westeurope.cloudapp.azure.com:9200" ]

# index at startup. Your Kibana users still need to authenticate with Elasticsearch, which
# is proxied through the Kibana server.
elasticsearch.username: "kibana_system"
elasticsearch.password: "uxnm3t5LHnkrUv2y7ou4"

# Enables SSL and paths to the PEM-format SSL certificate and SSL key files, respectively.
# These settings enable SSL for outgoing requests from the Kibana server to the browser.
server.ssl.enabled: true
server.ssl.certificate: /opt/kibana-7.16.2-linux-x86_64/config/elk6.crt 
server.ssl.key: /opt/kibana-7.16.2-linux-x86_64/config/elk6.key

# Optional settings that provide the paths to the PEM-format SSL certificate and key files.
# These files are used to verify the identity of Kibana to Elasticsearch and are required when
# xpack.security.http.ssl.client_authentication in Elasticsearch is set to required.
#elasticsearch.ssl.certificate: /path/to/your/client.crt
#elasticsearch.ssl.key: /path/to/your/client.key

# Optional setting that enables you to specify a path to the PEM file for the certificate
# authority for your Elasticsearch instance.
elasticsearch.ssl.certificateAuthorities: "/opt/kibana-7.16.2-linux-x86_64/config/elasticsearch-ca.pem"
# To disregard the validity of SSL certificates, change this setting's value to 'none'.
elasticsearch.ssl.verificationMode: none
xpack.encryptedSavedObjects.encryptionKey: 9b09de9795160ba96a34127cb1f5b04e
xpack.reporting.encryptionKey: 4d64b8dba607f5cf0348768b3bc6db7e
xpack.security.encryptionKey: 7d992112c83206ed57fdb2a0d4f22d77
xpack.security.session.idleTimeout: "1h"
xpack.security.session.lifespan: "30d"
xpack.reporting.roles.enabled: false
monitoring.kibana.collection.enabled: true

# Time in milliseconds to wait for Elasticsearch to respond to pings. Defaults to the value of
# the elasticsearch.requestTimeout setting.
#elasticsearch.pingTimeout: 1500
# Time in milliseconds to wait for responses from the back end or Elasticsearch. This value
# must be a positive integer.
logging.dest: /opt/logs/kibana.log
